# Generated by Django 6.0.3 on 2026-04-13 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=128, verbose_name='Хеш пароля')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Аккаунт активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'accounts_user',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=512, unique=True, verbose_name='Значение refresh-токена')),
                ('expires_at', models.DateTimeField(verbose_name='Срок действия')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Токен отозван')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='accounts.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Refresh-токен',
                'verbose_name_plural': 'Refresh-токены',
                'db_table': 'accounts_refresh_token',
                'indexes': [models.Index(fields=['user', 'is_revoked'], name='idx_rt_user_revoked')],
            },
        ),
    ]
