# Generated by Django 6.0.3 on 2026-04-13 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.SlugField(help_text='Уникальный идентификатор (например, «create»).', max_length=100, unique=True, verbose_name='Кодовое имя действия')),
                ('name', models.CharField(help_text='Например, «Создание».', max_length=200, verbose_name='Человекочитаемое название')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'db_table': 'rbac_action',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.SlugField(help_text='Уникальный идентификатор ресурса в нижнем регистре (например, «documents»).', max_length=100, unique=True, verbose_name='Кодовое имя ресурса')),
                ('name', models.CharField(help_text='Например, «Документы».', max_length=200, verbose_name='Человекочитаемое название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание ресурса')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'db_table': 'rbac_resource',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.SlugField(help_text='Уникальный идентификатор роли (например, «admin»).', max_length=100, unique=True, verbose_name='Кодовое имя роли')),
                ('name', models.CharField(help_text='Например, «Администратор».', max_length=200, verbose_name='Человекочитаемое название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'rbac_role',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rbac.action', verbose_name='Действие')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rbac.resource', verbose_name='Ресурс')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rbac.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешения',
                'db_table': 'rbac_permission',
                'ordering': ['role', 'resource', 'action'],
                'unique_together': {('role', 'resource', 'action')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Назначение роли',
                'verbose_name_plural': 'Назначения ролей',
                'db_table': 'rbac_user_role',
                'ordering': ['user', 'role'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
